### ISSUE TITLE
Improve imagery location selection

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-uploader#40]
Uploading imagery has a couple barriers, one of them being the requirement of having the imagery stored somewhere publicly accessible - a file server, Dropbox, Google Drive, etc. A challenge with Dropbox and Google Drive is that direct download links are hidden. If you select a share URL from these services, the uploader will error when trying to consume the data. 

![](https://api.monosnap.com/rpc/file/download?id=gBUSU2IN0dXnlyuHCAm4FWbLwZBBtY)

Goal here is to improve the process. Give better instructions for how the imagery needs to be temporarily stored somewhere like Dropbox, make it foolproof to fill out the form and contribute imagery. 

Need to draft an outline for how this could be improved. Some of the ideas thought about draw some inspiration from how HDX has improved their workflow: http://docs.humdata.org/adding-data-is-now-easier-on-hdx/#more-2496. Discussion on github [here](https://github.com/OCHA-DAP/hdx-ckan/issues/3889).

**Comment by danielfdsilva** [comment]
Current state:
The imagery location selector was improved to support integration with Dropbox and direct url input. Instead of having a big text area, now each file has its own field, making it less error prone.

The integration with gDrive is not implement yet because google's api does not provide a straightforward way to do it. Aside from the fact that the file has to be publicly available (shared), the [google picker](https://developers.google.com/picker/docs/) doesn't seem to provide a direct url to the file. There's always a redirect. This is problematic because the uploader api is not capable of handling redirection.

**Comment by danielfdsilva** [comment]
Been looking into the gdrive situation.
The library used for the image download ([request](https://github.com/request/request)) seems to indeed be able to handle redirects and does it by default (according to the docs).

Using the google picker we are able to get a download link that does not require authentication but only for files that are publicly available. We'd need to add this note somewhere. Much like described here: https://github.com/OCHA-DAP/hdx-ckan/issues/3889#issuecomment-172260200

@smit1678 thoughts?

**Comment by smit1678** [comment]
@danielfdsilva Cool, ok that makes sense and agreed on the documentation side of things. I'll run some quick tests to see if the uploader automatically handles the redirects.

**Comment by smit1678** [comment]
Implemented
